Repository codam-coding-college/MLX42, pull requests merged in 2022-03, with the labels that each got.

#17 Refactor everything to remove the norme
  .github/workflows/ci.yml
  include/MLX42/MLX42.h
  include/MLX42/MLX42_Int.h
  include/MLX42/MLX42_Keys.h
  src/font/mlx_font.c
  src/mlx_cursor.c
  src/mlx_exit.c
  src/mlx_images.c
  src/mlx_init.c
  src/mlx_keys.c
  src/mlx_loop.c
  src/mlx_monitor.c
  src/mlx_mouse.c
  src/mlx_put_pixel.c
  src/mlx_shader.c
  src/mlx_window.c
  src/textures/mlx_png.c
  src/textures/mlx_texture.c
  src/textures/mlx_xpm42.c
  src/textures/mlx_xpm42_utils.c
  src/utils/mlx_error.c
  src/utils/mlx_hash.c
  src/utils/mlx_image_utils.c
  src/utils/mlx_list.c
  src/utils/mlx_list_utils.c
  src/utils/mlx_utils.c
  src/utils/mlx_window_utils.c
  tools/compile_shader.py
Labels: Request, Fix

#19 Proof-of-concept: Batched rendering
  include/MLX42/MLX42_Int.h
  shaders/default.frag
  shaders/default.vert
  src/mlx_images.c
  src/mlx_init.c
  src/mlx_loop.c
Labels: Request, Fix

#18 Replace compile_shader script with bash variant
  .gitattributes
  .github/workflows/ci.yml
  Makefile
  Makefile_Unix.mk
  Makefile_WindowsNT.mk
  tools/compile_shader.bat
  tools/compile_shader.py
  tools/compile_shader.sh
Labels: Request

#22 Add generic homebrew path finding option to work with custom homebrew…
  Makefile
Labels: Improvement

#25 Fix endian dependent color reading
  src/textures/mlx_xpm42.c
Labels: Fix

#26 Implement assertions to check for null
  Makefile
  include/MLX42/MLX42.h
  src/font/mlx_font.c
  src/mlx_cursor.c
  src/mlx_exit.c
  src/mlx_images.c
  src/mlx_loop.c
  src/textures/mlx_png.c
  src/textures/mlx_texture.c
  src/textures/mlx_xpm42.c
  src/utils/mlx_error.c
  src/utils/mlx_utils.c
Labels: Improvement

#24 Makefile cleanup and fixes
  .github/workflows/ci.yml
  .gitignore
  Makefile
  Makefile_Unix.mk
  Makefile_WindowsNT.mk
  include/MLX42/MLX42_Int.h
  src/textures/mlx_xpm42.c
  src/utils/mlx_utils.c
  tools/compile_shader.bat
  tools/compile_shader.sh
Labels: Fix, Improvement
