Repository codam-coding-college/MLX42, pull requests merged in 2022-08, with the labels that each got.

#44 Back to using faster `mlx_lstadd_front`
  src/mlx_images.c
Labels: Fix

#48 Added WSL set up steps
  README.md
Labels: Documentation, Improvement

#51 Improve README
  README.md
Labels: Documentation, Fix

#42 Make-it-pretty.mk dude.
  Makefile_Unix.mk
Labels: Improvement

#54 Fix images not appearing
  include/MLX42/MLX42.h
  include/MLX42/MLX42_Int.h
  src/font/mlx_font.c
  src/mlx_exit.c
  src/mlx_images.c
  src/mlx_init.c
  src/mlx_loop.c
  src/mlx_window.c
  src/utils/mlx_list.c
  src/utils/mlx_render_queue_sort.c
  src/utils/mlx_vec.c
Labels: Fix
