Repository codam-coding-college/MLX42, pull requests merged in 2022-11, with the labels that each got.

#60 fixed xpm deallocation and switched from int to double for mlx_get_time (more precision)
  include/MLX42/MLX42.h
  src/textures/mlx_xpm42.c
  src/utils/mlx_utils.c
Labels: Fix, Improvement

#64 Update Basics.md
  docs/Basics.md
Labels: Documentation

#63 Code cleanup and fixed some typos
  docs/Basics.md
  docs/Colors.md
  docs/Hooks.md
  docs/Images.md
  docs/Input.md
  docs/Shaders.md
  docs/Textures.md
  docs/XPM42.md
  docs/index.md
  src/mlx_cursor.c
  src/mlx_exit.c
  src/mlx_window.c
  src/utils/mlx_error.c
  src/utils/mlx_list.c
  src/utils/mlx_utils.c
Labels: Documentation, Fix
