Repository codam-coding-college/MLX42, pull requests merged in 2023-02, with the labels that each got.

#73 Typos and cleanup
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  docs/Colors.md
  docs/Hooks.md
  docs/Images.md
  docs/Input.md
  docs/Shaders.md
  docs/Textures.md
  docs/XPM42.md
  docs/index.md
  src/utils/mlx_comparison.c
  src/utils/mlx_list.c
Labels: Documentation

#70 Rework build system & refactor code for 2.3.0
  .github/workflows/ci.yml
  .gitignore
  CMakeLists.txt
  Makefile
  Makefile_Unix.mk
  Makefile_WindowsNT.mk
  README.md
  VERSION.md
  cmake/LinkGLFW.cmake
  docs/Basics.md
  docs/assets/XPM_Demo.png
  docs/assets/logo.png
  docs/index.md
  include/MLX42/MLX42.h
  include/MLX42/MLX42_Int.h
  include/ctest/LICENSE
  include/ctest/README.md
  include/ctest/ctest.h
  src/utils/mlx_compare.c
  src/utils/mlx_error.c
  test/Makefile
  test/Tester.h
  test/src/img_del_test.c
  test/src/init_test.c
  test/src/prim_str_draw.c
  test/src/put_pixel_test.c
  tests/Makefile
  tests/tests.c
  tests/unit.c
  tools/compile_shader.bat
  tools/compile_shader.sh
  tools/xpm3_conv.py
Labels: Fix, Improvement

#74 Cmake fix
  CMakeLists.txt
  README.md
Labels: Documentation, Fix

#75 Typos and documentation fix
  README.md
  docs/42.md
Labels: Documentation

#77 Typos
  README.md
  docs/42.md
  docs/index.md
  include/MLX42/MLX42.h
  src/font/mlx_font.c
Labels: Documentation

#80 Update order of README #79
  README.md
Labels: Documentation

#81 Fix README code example compile error
  README.md
Labels: Documentation, Fix

#84 Cmake doesn't override glfw_FOUND when set manually + README update
  CMakeLists.txt
  README.md
  cmake/Findglfw3.cmake
  docs/index.md
Labels: Improvement

#86 README fix
  README.md
Labels: Documentation

#87 Add frameworks for macOS
  CMakeLists.txt
Labels: Improvement

#90 Change testing framework to CMake
  .github/workflows/ci.yml
  CMakeLists.txt
  include/ctest/LICENSE
  include/ctest/README.md
  include/ctest/ctest.h
  tests/CMakeLists.txt
  tests/Makefile
  tests/test.h
  tests/tests.c
  tests/tests.cpp
  tests/unit.c
Labels: Improvement
